### ISSUE TITLE
Version is not set in pyproject.toml

### ISSUE THREAD

**Issue by dvzrv** [ludeeus/awesomeversion#136]
### The problem

Hi! The pyproject.toml of this project declares the version of this project as 0, which is wrong.
The correct version of the python project needs to be declared there (see [relevant poetry documentation](https://python-poetry.org/docs/pyproject/#version))

### Operating system

Arch Linux

### Python version

3.10

### Problem-relevant code

https://github.com/ludeeus/awesomeversion/blob/736f1fce7a80042124c71100fc4bcdaff6d5543d/pyproject.toml#L21

### Additional information

If the project's version is not set, sdist tarballs and wheels built from it will have wrong metadata set. This means that other projects will not be able to rely on it without the built package being patched beforehand (they will not be able to use the version information).

This is problematic in general version resolution as well as in system's packaging.

**Comment by ludeeus** [comment]
This is set during the release workflow <https://github.com/ludeeus/awesomeversion/blob/main/.github/workflows/release.yml#L25-L28>

**Comment by dvzrv** [comment]
Okay, but that allows noone to build this project from this git repository or a tarball created from a tag in this repository.
More specifically this allows noone to run tests, as those are not included in the sdist tarball on pypi.org

Please consider changing the workflow as it is limiting the use of this library and/or adding the tests to the sdist tarball.
