### ISSUE TITLE
Version comparison throws

### ISSUE THREAD

**Issue by zweckj** [ludeeus/awesomeversion#333]
### The problem

Coming from this issue with update entities in HA (https://github.com/home-assistant/core/issues/120264). awesomeversion can't compare the version strings `v3.6-rc2` and `v3.4-rc5`

### Operating system

Win/HAOS/WSL

### Python version

3.11

### Problem-relevant code

```python
>>> AwesomeVersion("v3.4-rc5") > "v3.6-rc2"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zweckj/dev/home-assistant-core/venv/lib/python3.12/site-packages/awesomeversion/awesomeversion.py", line 188, in __gt__
    raise AwesomeVersionCompareException(
awesomeversion.exceptions.AwesomeVersionCompareException: Can't compare <unknown v3.4-rc5> and <unknown v3.6-rc2>
```

**Comment by ludeeus** [comment]
Please provide the details of what version strategy this is.

**Comment by zweckj** [comment]
@ludeeus I have no idea tbh. The strings are taken from their API as is. I'm not sure I understand the regexes. I normally use `versions` for version checks (which handles that string just fine), just ended up at `awesomeversion` because of the aforementioned HA bug.

**Comment by zweckj** [comment]
I think `PEP440` might just need `[vV]?` at the beginning

**Comment by zweckj** [comment]
Wow that was quick, thanks! Will you make a release out of this?

**Comment by ludeeus** [comment]
Yes, but probably not until later this week.
